services:
  bot:
    build: ./bot
    container_name: grade-monitor-bot
    restart: unless-stopped
    network_mode: host
    env_file:
      - ./bot/.env
    environment:
      - DRIVER=~websockets
      - ONEBOT_WS_URLS=["ws://127.0.0.1:3001"]
    volumes:
      - ./bot/src:/app/src
      - ./data:/app/data
